module.exports = [
  {
    id: 'newspaper',
    type: 'newspaper',
    outlet: '한빛일보',
    byline: '김빠름 기자',
    date: '2025-09-03',
    headline: '한빛시 공원 일대 킥보드 수백 대 무단 방치... 시민 통행 불편',
    body: '한빛시 중앙공원 인근에 개인형 이동장치 수백 대가 인도와 공원 입구를 점령해 시민 통행에 불편을 주고 있다. 시 관계자는 "관련 조례 마련을 검토 중"이라고 밝혔다.',
    imageAlt: '[사진: 킥보드가 뒤엉킨 공원 입구]',
  },
  {
    id: 'broadcast',
    type: 'broadcast',
    outlet: 'HB뉴스',
    headline: '킥보드 수백 대 점령한 공원... 시민 분통',
    script: '시민들의 쉼터가 되어야 할 공원이 킥보드 무덤이 됐습니다. 오늘도 수백 대의 킥보드가 방치된 채 발견됐습니다.',
    ticker: '속보 | 한빛시 킥보드 무단방치 민원 이번 달만 200건 돌파',
  },
  {
    id: 'sns',
    type: 'sns',
    username: '@hanbit_life',
    handle: '한빛시 사는 사람',
    content: '공원 나왔더니 킥보드 밭이네요 진짜 ㅋㅋㅋ 이거 어디다 신고해요?? 너무 불편 #한빛시 #킥보드 #민폐',
    likes: 1823,
    comments: 247,
    shares: 512,
    timeAgo: '3시간 전',
  },
  {
    id: 'youtube',
    type: 'youtube',
    channel: '한빛시 고발단',
    thumbnail: '[썸네일: 충격 표정 + 킥보드 사진]',
    title: '충격) 한빛시 공원 킥보드 직접 가봤습니다... 이건 진짜 심각합니다',
    views: '38만회',
    likes: '1.2만',
    uploadedAt: '1일 전',
    description: '직접 현장 취재해봤습니다. 제 눈을 의심했어요...',
  },
];
